### PR TITLE
Update for Spigot 1.12.2

### PR DESCRIPTION
**Pull request by quinnshultz**
I have updated the dependencies to compile for CraftBukkit / Spigot 1.12.2. I currently working on replacing deprecated methods, fixing calls to methods that no longer exist, and unit testing in order to build for 1.13.2.

### CODE REVIEW

**Comment by quinnshultz** [comment]
Is it possible to update the resource on spigotmc.org? If @nextinfinity is too occupied to create a build, I have created one for CB 1.12.2 at: http://ci.quinnshultz.com/view/Minecraft%20Plugins/job/Super%20Craft%20Bros/5/artifact/build/libs/SuperCraftBros-1.7.2.jar

**Comment by nextinfinity** [comment]
I'm happy to merge this into the legacy branch, but the code is currently undergoing a significant rewrite in the dev branch and I do not plan to maintain this version of the code beyond Minecraft version 1.12.

**Comment by quinnshultz** [comment]
That sounds good to me! I'm excited to pull your dev branch changes.

**Comment by nextinfinity** [comment]
I do appreciate your desire to contribute - I actually got a message on Spigot a couple weeks ago requesting an update to 1.13.2 and upon looking at the code it seems it makes more sense to migrate to a game core I've been working on. There's some weird side effects of this change (mainly, the actual SCB repo will be very slim after this, and arenas will now be worldedit schematics), but it should allow for easier maintainability.

**Comment by quinnshultz** [comment]
Very cool, I am excited to contribute. I apologize if my change to the version number was incorrect. In the future, I will let you handle details like that.

 I would be happy to write Javadoc comments for public classes and methods. I am also more that happy to write some JUnit test cases for the new version. I also see that one of the open issues requests custom items, this seems doable as an extension of the custom character classes. Please let me know how I can help!

**Pull request merged**
